replicaCount: 2

image:
  repository: <your-dockerhub-username>/nodejs-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  port: 80
